In [35]:
# search thresholds for imbalanced classification
import numpy as np
from numpy import argmax
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

In [22]:
# apply threshold to positive probabilities to create labels
def to_labels(pos_probs, threshold):
	return (pos_probs >= threshold).astype('int')

In [23]:
probs = [[0.5795, 0.4205],
 [0.6629, 0.3371],
 [0.7313, 0.2687],
 [0.6728, 0.3272],
 [0.5086, 0.4914]]
probs

[[0.5795, 0.4205],
 [0.6629, 0.3371],
 [0.7313, 0.2687],
 [0.6728, 0.3272],
 [0.5086, 0.4914]]

In [24]:
type(probs)

list

In [25]:
array_probs = np.array(probs)
array_probs

array([[0.5795, 0.4205],
       [0.6629, 0.3371],
       [0.7313, 0.2687],
       [0.6728, 0.3272],
       [0.5086, 0.4914]])

In [26]:
p_probs = array_probs[:,1]
p_probs

array([0.4205, 0.3371, 0.2687, 0.3272, 0.4914])

In [40]:
to_labels(p_probs,0.3)

array([1, 1, 0, 1, 1])

In [ ]:
for threshold in np.arange(0, 0.3, 0.02):
    predicted_valid = (probabilities_one_valid >= threshold).astype('int')
    precision = precision_score(target_valid,predicted_valid)
    recall = recall_score(target_valid,predicted_valid)
    print('Threshold = {:.2f} | Precision = {:.3f}, Recall = {:.3f}'.format(threshold, precision, recall))

In [33]:
for t in np.arange(0, 0.5, 0.02):
    print('Threshold: ', t, 'Positives: ', (to_labels(p_probs,t)==1).sum())

Threshold:  0.0 Positives:  5
Threshold:  0.02 Positives:  5
Threshold:  0.04 Positives:  5
Threshold:  0.06 Positives:  5
Threshold:  0.08 Positives:  5
Threshold:  0.1 Positives:  5
Threshold:  0.12 Positives:  5
Threshold:  0.14 Positives:  5
Threshold:  0.16 Positives:  5
Threshold:  0.18 Positives:  5
Threshold:  0.2 Positives:  5
Threshold:  0.22 Positives:  5
Threshold:  0.24 Positives:  5
Threshold:  0.26 Positives:  5
Threshold:  0.28 Positives:  4
Threshold:  0.3 Positives:  4
Threshold:  0.32 Positives:  4
Threshold:  0.34 Positives:  2
Threshold:  0.36 Positives:  2
Threshold:  0.38 Positives:  2
Threshold:  0.4 Positives:  2
Threshold:  0.42 Positives:  2
Threshold:  0.44 Positives:  1
Threshold:  0.46 Positives:  1
Threshold:  0.48 Positives:  1


In [36]:
# generate dataset
X, y = make_classification(n_samples=10000, n_features=2, n_redundant=0,
	n_clusters_per_class=1, weights=[0.99], flip_y=0, random_state=4)

In [38]:
y

array([0, 0, 0, ..., 0, 0, 0])